### ISSUE TITLE
 category_mapping.tsv and object_bbox_v2.json 

### ISSUE THREAD

**Issue by jasscia18** [CrystalSixone/DSRG#4]
您好，请问R2R和REVERIE数据集中使用的是一样的category_mapping.tsv and object_bbox_v2.json 吗？作者目前只上传了R2R数据集的？可以上传REVERIE数据集的这两个文件吗？

**Comment by CrystalSixone** [comment]
您好，感谢您的提醒，R2R和REVERIE中这两个文件是一样的，已在readme中修正了路径。
