### ISSUE TITLE
REVERIE dataset的复现结果

### ISSUE THREAD

**Issue by jasscia18** [CrystalSixone/DSRG#5]
您好，我按照[README.md]对REVERIE数据集进行了重新微调，但结果与论文相差很多。
![LCTBKBG1M~_5ZV EPX%WH@5](https://github.com/CrystalSixone/DSRG/assets/43958686/34a1aaaa-1d4c-4160-9539-7721a53f2829)
您可以帮我看看是哪里出现的问题吗？我使用了作者上传的model_step_best_148000.pt，由于网络原因离线下载了distilbert-base-uncased的【config.json，pytorch_model.bin，vocab.txt】。放到了这两个地方，其他地方与论文一致。
![P0~IM 4R30M%5I5J 8WBO5A](https://github.com/CrystalSixone/DSRG/assets/43958686/698fe9d5-2b1b-4f44-9121-83fb0b37f5e5)
![0QPX(0@NFQ (JX7TW2JTI9G](https://github.com/CrystalSixone/DSRG/assets/43958686/9239c2de-2000-4958-82c5-071e5cb131fd)

**Comment by CrystalSixone** [comment]
是否是因为没有正确加载category_mapping.tsv和object_bbox_v2.json的原因？我已在Readme中修正了这两个文件的路径。

**Comment by jasscia18** [comment]
您好，我已经正确加载了category_mapping.tsv和object_bbox_v2.json，但还是不能复现出论文的结果。我考虑是不是因为下面的原因？在vlnbert_init.py中的
![image](https://github.com/CrystalSixone/DSRG/assets/43958686/1a872a79-a201-46ac-8d83-a4238a23869d)
我在训练时，一直报错显示
![image](https://github.com/CrystalSixone/DSRG/assets/43958686/233d8b42-5606-4877-9579-be4c94710115)
所以，我把代码修改为了
![image](https://github.com/CrystalSixone/DSRG/assets/43958686/63e59149-d416-4608-b62a-f0fd5cb8d8bd)
请问这样修改是否可以？应该怎么修改？

**Comment by CrystalSixone** [comment]
那应该是预训练模型没有正确加载，可以在训练的时候传入`--eval_first`参数，检查下微调前的预训练模型性能。
你截图中的那段代码是通过`state_dict=new_ckpt_weights`加载预训练模型的。
出现报错应该是版本问题导致的，我建议您尝试下修改对应库的版本和`requirements.txt`中提供的一致。

**Comment by jasscia18** [comment]
非常感谢！！！
