### ISSUE TITLE
R2R数据集中的obj特征

### ISSUE THREAD

**Issue by jasscia18** [CrystalSixone/DSRG#8]
你好，请问在R2R数据集中，是没有用到obj特征吗？在代码vilmodel.py中的ImageEmbeddings函数中，发现bs, view_len, obj_len = traj_obj_img_fts.shape[0], traj_obj_img_fts.shape[1], traj_obj_img_fts.shape[2] 的，**traj_obj_img_fts**特征为None。

**Comment by CrystalSixone** [comment]
Thank you for the reminder! The error occurred due to the cleaning code not properly updating the parameter names, an issue that I have now rectified.
